### ISSUE TITLE
Module not found: Can't resolve 'react-star-rating-component'

### ISSUE THREAD

**Issue by Siddhant-Goswami** [saranshbansal/food-order-app-reactjs#1]
![Screenshot from 2020-07-26 13-49-34](https://user-images.githubusercontent.com/32980158/88474757-53932000-cf47-11ea-948d-bc250560ef03.png)

**Comment by saranshbansal** [comment]
Hi, I've updated the repository with missing n outdated packages (2 years worth of update) and also made it usable again by updating the mock data link.

**Comment by Lalith514** [comment]
try,
npm install react-star-ratings --force

**Comment by Lalith514** [comment]
npm i react-star-rating-component
